workflows:
  ios-device-build:
    name: iOS Device Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Preload Metal Toolchain Components
        script: |
          xcodebuild -downloadComponent MetalToolchain
      - name: Native Automated iOS Compilation
        script: |
          # Uses Codemagic's official tool to automatically locate paths and package a development build
          xcode-project build-ipa \
            -workspace DuoLikeAnimation.xcworkspace \
            -scheme DuoLikeAnimation
    artifacts:
      - build/ios/ipa/*.ipa
