workflows:
  ios-device-build:
    name: iOS Device Build
    max_build_duration: 30
    instance_type: mac_mini_m2
    environment:
      xcode: latest
      cocoapods: default
    scripts:
      - name: Preload Metal Toolchain Components
        script: |
          xcodebuild -downloadComponent MetalToolchain
      - name: Native Automated iOS Compilation
        script: |
          # Corrected file layout properties and fixed the spelling typo
          xcode-project build-ipa \
            --project DuoLikeAnimation.xcodeproj \
            --scheme DuoLikeAnimation
    artifacts:
      - build/ios/ipa/*.ipa
